package com.byterexx.document.report.vo;

public enum ReportType {
    LOCKED_OUT_USERS_REPORT,
    USER_PREFERENCES_REPORT, 
    ACTIVE_ADMIN_USERS_REPORT, 
    APPLICATION_NOTIFICATIONS_REPORT, 
    BOUNCE_BACK_REPORT, 
    DISCLOSURE_REPORT, 
    CONSENT_SUMMARY_REPORT, 
    EMAIL_SUMMARY_REPORT, 
    IFS_KEY_NOTIFICATION_REPORT, 
    PORTAL_USAGE_LOG_REPORT; 
}
